import React from "react";
import figma from "@figma/code-connect";
import { Checkbox } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=176%3A7554",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("size", {
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      isInvalid: figma.boolean("isInvalid"),
      label: figma.string("label"),
      indeterminate: figma.enum("body", {
        indeterminate: true,
      }),
      defaultChecked: figma.enum("body", {
        checked: true,
      }),
      isDisabled: figma.enum("state", {
        disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "isLabel": figma.boolean('isLabel'),
      // "isFocused": figma.boolean('isFocused'),
    },
    example: props => (
      <Checkbox
        size={props.size}
        isInvalid={props.isInvalid}
        label={props.label}
        indeterminate={props.indeterminate}
        isDisabled={props.isDisabled}
        defaultChecked={props.defaultChecked}
      />
    ),
  }
);
