import React from "react";
import figma from "@figma/code-connect";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SelectTrigger,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=139%3A22300",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("size", {
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      isInvalid: figma.enum("isInvalid", {
        false: false,
        true: true,
      }),
      disabled: figma.enum("state", {
        disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "isFocused": figma.boolean('isFocused'),
      value: figma.string("value"),
    },
    example: props => (
      <Select>
        <SelectTrigger
          size={props.size}
          isInvalid={props.isInvalid}
          disabled={props.disabled}
        >
          <SelectValue placeholder={props.value} />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="option1">Option 1</SelectItem>
          <SelectItem value="option2">Option 2</SelectItem>
          <SelectItem value="option3">Option 3</SelectItem>
        </SelectContent>
      </Select>
    ),
  }
);
