import React from "react";
import { Button } from "@/components/button";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-UI?node-id=233-5071",
  {
    props: {
      prefixIcon1164197: figma.instance("prefixIcon"),
      label4128108: figma.string("label"),
      isPrefixIcon36859: figma.boolean("isPrefixIcon"),
      isSuffixIcon36858: figma.boolean("isSuffixIcon"),
      suffixIcon11641278: figma.instance("suffixIcon"),
      isFocused22950: figma.boolean("isFocused"),
      state: figma.enum("state", {
        enable: "enable",
        hover: "hover",
        active: "active",
        loading: "loading",
        disabled: "disabled",
      }),
      size: figma.enum("size", {
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      variant: figma.enum("variant", {
        solid: "solid",
        outline: "outline",
        ghost: "ghost",
      }),
      theme: figma.enum("theme", {
        primary: "primary",
        secondary: "secondary",
        negative: "negative",
      }),
      label: figma.string("button"),
    },
    example: (props) => (
      <Button variant={props.variant} size={props.size} theme={props.theme} />
    ),
  }
);
