import React from "react";
import figma from "@figma/code-connect";
import { Slider } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Slider,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15094%3A965",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("state", {
        disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "value": figma.string('value'),
      // "position": figma.enum('position', {
      //   "0%": "0-",
      //   "20%": "20-",
      //   "40%": "40-",
      //   "60%": "60-",
      //   "80%": "80-",
      //   "100%": "100-"
      // })
    },
    example: props => <Slider disabled={props.disabled} />,
  }
);
