import React from "react";
import figma from "@figma/code-connect";
import { Skeleton } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Skeleton,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=24%3A131",
  {
    props: {},
    example: props => <Skeleton />,
  }
);
