import React from "react";
import figma from "@figma/code-connect";
import { Button } from "../button";
import {
  Modal,
  ModalBody,
  ModalClose,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalTitle,
  ModalTrigger,
} from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Modal,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1306%3A20954",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // isHeader: figma.boolean("isHeader"),
      // isFooter: figma.boolean("isFooter"),
      // isCloseTrigger: figma.boolean("isCloseTrigger"),
      title: figma.string("title"),
      size: figma.enum("size", {
        sm: "sm",
        md: "md",
        lg: "lg",
        xl: "xl",
        full: "full",
      }),
    },
    example: props => (
      <Modal>
        <ModalTrigger>モーダルを開く</ModalTrigger>
        <ModalContent size={props.size}>
          <ModalHeader>
            <ModalTitle>{props.title}</ModalTitle>
            <ModalClose />
          </ModalHeader>
          <ModalBody>
            <p>スロット</p>
          </ModalBody>
          <ModalFooter>
            <Button size="sm" theme="neutral" variant="ghost">
              キャンセル
            </Button>
            <Button size="sm">保存</Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    ),
  }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ModalBody,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=2893%3A25363",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      isSpace: figma.boolean("isSpaced"),
      // No matching props could be found for these Figma properties:
      // "slot": figma.instance('slot')
    },
    example: props => <ModalBody isSpace={props.isSpace} />,
  }
);

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ModalFooter,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=2893%3A25357",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "slot": figma.instance('slot'),
      // "type": figma.enum('type', {
      //   "default": "default",
      //   "slot": "slot"
      // })
    },
    example: props => <ModalFooter />,
  }
);
