import React from "react";
import figma from "@figma/code-connect";
import { useForm } from "react-hook-form";
import { Input } from "../input";
import {
  Form,
  FormErrorMessage,
  FormHeader,
  FormHelperMessage,
  FormControl,
  FormField,
  FormItem,
} from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

// figma.connect(
//   Form,
//   "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1274%3A66278",
//   {
//     props: {
//       // No matching props could be found for these Figma properties:
//       // "isErrorMessage": figma.boolean('isErrorMessage'),
//       // "isHelpMessage": figma.boolean('isHelpMessage')
//     },
//     example: props => {
//       return (
//         <Form {...UseFormReturnType}>
//           <FormField
//             name="example"
//             render={({ field, fieldState }) => (
//               <FormItem>
//                 <FormHeader label="ラベル" />
//                 <FormHelperMessage>ヘルプメッセージ</FormHelperMessage>
//                 <FormControl>
//                   <Input
//                     placeholder="入力してください"
//                     {...field}
//                     {...fieldState}
//                     isInvalid={fieldState.invalid}
//                   />
//                 </FormControl>
//                 <FormErrorMessage />
//               </FormItem>
//             )}
//           />
//         </Form>
//       );
//     },
//   }
// );

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  FormErrorMessage,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=573%3A6321",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "label": figma.string('label')
    },
    example: props => <FormErrorMessage />,
  }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  FormHeader,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=573%3A4867",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("label"),
      isRequired: figma.boolean("isRequired"),
      // No matching props could be found for these Figma properties:
      helpText: figma.boolean("isHintTrigger", {
        true: "有効",
        false: undefined,
      }),
    },
    example: props => (
      <FormHeader
        label={props.label}
        isRequired={props.isRequired}
        helpText={props.helpText}
      />
    ),
  }
);

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  FormHelperMessage,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=574%3A10563",
  {
    props: {
      // No matching props could be found for these Figma properties:
      label: figma.string("label"),
    },
    example: props => <FormHelperMessage>{props.label}</FormHelperMessage>,
  }
);

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  FormControl,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=2831%3A2244",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "unitLabel1": figma.string('unitLabel 1'),
      // "unitLabel2": figma.string('unitLabel 2'),
      // "unitLabel3": figma.string('unitLabel 3'),
      // "isShowUnitLabel": figma.boolean('isShowUnitLabel'),
      // "type": figma.enum('type', {
      //   "input": "input",
      //   "input unit 2": "input-unit-2",
      //   "input range": "input-range",
      //   "number": "number",
      //   "number range": "number-range",
      //   "select": "select",
      //   "select range": "select-range",
      //   "date": "date",
      //   "date range": "date-range",
      //   "time": "time",
      //   "time range": "time-range",
      //   "password": "password",
      //   "file": "file",
      //   "textarea": "textarea",
      //   "radio": "radio",
      //   "checkbox": "checkbox",
      //   "input unit 3": "input-unit-3"
      // })
    },
    example: props => (
      <FormControl>
        <Input placeholder="入力してください" />
      </FormControl>
    ),
  }
);
