import React from "react";
import figma from "@figma/code-connect";
import { Tooltip, TooltipContent, TooltipTrigger } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TooltipContent,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=973%3A684",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      side: figma.enum("side", {
        top: "top",
        right: "right",
        bottom: "bottom",
        left: "left",
      }),
      // No matching props could be found for these Figma properties:
      label: figma.string("label"),
    },
    example: props => (
      <Tooltip>
        <TooltipTrigger>Tooltip Trigger</TooltipTrigger>
        <TooltipContent side={props.side}>{props.label}</TooltipContent>
      </Tooltip>
    ),
  }
);
