import * as React from "react";
import figma from "@figma/code-connect";
import { Button } from "./index";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/nJ7LHYsXvqN6PwhOwknc8R/Sparkle-UI-for-MCP?node-id=233-5071",
  {
    props: {
      state: figma.enum("state", {
        default: "default",
        hover: "hover",
        active: "active",
        disabled: "disabled",
        loading: "loading",
      }),
      variant: figma.enum("variant", {
        solid: "solid",
        outline: "outline",
        ghost: "ghost",
      }),
      size: figma.enum("size", {
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      theme: figma.enum("theme", {
        primary: "primary",
        secondary: "secondary",
        negative: "negative",
      }),
      children: figma.string("label"),
      prefixIcon: figma.string("prefixIcon"),
      suffixIcon: figma.string("suffixIcon"),
    },
    example: props => (
      <Button
        variant={props.variant}
        size={props.size}
        theme={props.theme}
        isLoading={props.state === "loading"}
        isDisabled={props.state === "disabled"}
        prefixIcon={props.prefixIcon}
        suffixIcon={props.suffixIcon}
      >
        {props.children || "Button"}
      </Button>
    ),
  }
);

export function examples() {
  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap gap-2">
        <Button theme="primary">Primary</Button>
        <Button theme="secondary">Secondary</Button>
        <Button theme="negative">Negative</Button>
      </div>

      <div className="flex flex-wrap gap-2">
        <Button theme="negative">Solid</Button>
        <Button theme="negative">Outline</Button>
        <Button theme="negative">Ghost</Button>
      </div>

      <div className="flex flex-wrap gap-2">
        <Button size="sm">Small</Button>
        <Button size="md">Medium</Button>
        <Button size="lg">Large</Button>
      </div>

      <div className="flex flex-wrap gap-2">
        <Button>有効</Button>
        <Button isLoading>Loading</Button>
        <Button isDisabled>Disabled</Button>
      </div>

      <div className="flex flex-wrap gap-2">
        <Button prefixIcon="add">with Prefix Icon</Button>
        <Button suffixIcon="open_in_new">with Suffix Icon</Button>
        <Button prefixIcon="favorite" suffixIcon="open_in_new">
          with Both Icon
        </Button>
      </div>
    </div>
  );
}
