import React from "react";
import figma from "@figma/code-connect";
import { Button } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=11672%3A4288",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("size", {
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      variant: figma.enum("variant", {
        solid: "solid",
        outline: "outline",
        ghost: "ghost",
      }),
      theme: figma.enum("theme", {
        primary: "primary",
        neutral: "neutral",
        negative: "negative",
      }),
      isLoading: figma.enum("state", {
        loading: true,
      }),
      isDisabled: figma.enum("state", {
        disabled: true,
      }),
      disabled: figma.enum("state", {
        disabled: true,
      }),
      label: figma.string("label"),
      // No matching props could be found for these Figma properties:
      // "isFocused": figma.boolean('isFocused'),
      suffixIcon: figma.boolean("isSuffixIcon", {
        // FIXME: 複数箇所でアイコンのインスタンスを参照しようとするとCode Connectがエラーになるためコメントアウト中
        // true: figma.instance("suffixIcon").getProps<{
        //   icon: string;
        //   size: number;
        //   fill: boolean;
        // }>(),
        true: "expand_more",
        false: undefined,
      }),
      prefixIcon: figma.boolean("isPrefixIcon", {
        true: figma.instance("prefixIcon").getProps<{
          icon: string;
          size: number;
          fill: boolean;
        }>(),
        false: undefined,
      }),
    },
    example: props => (
      <Button
        size={props.size}
        variant={props.variant}
        theme={props.theme}
        isLoading={props.isLoading}
        isDisabled={props.isDisabled}
        disabled={props.disabled}
        prefixIcon={props.prefixIcon?.icon}
        suffixIcon={props.suffixIcon}
      >
        {props.label}
      </Button>
    ),
  }
);
