import React from "react";
import { Spinner } from ".";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Spinner, "", {
  props: {
    className: figma.string("className"),
  },
  example: (props) => <Spinner className={props.className} />,
});
