import React from "react";
import { Icon } from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Icon, "", {
  props: {
    icon: figma.string("icon"),
    className: figma.string("className"),
  },
  example: (props) => (
    <Icon icon={props.icon || "home"} className={props.className} />
  ),
});
