import React from "react";
import figma from "@figma/code-connect";
import { InputPassword } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  InputPassword,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=174%3A3296",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("size", {
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      disabled: figma.enum("state", {
        disable: true,
      }),
      isFocused: figma.boolean("isFocused"),
      isInvalid: figma.boolean("isInvaild"),
      defaultValue: figma.boolean("isEmpty", {
        true: undefined,
        false: figma.string("value"),
      }),
      placeholder: figma.boolean("isEmpty", {
        true: figma.string("value"),
        false: undefined,
      }),
      // No matching props could be found for these Figma properties:
      // "isFocused": figma.boolean('isFocused'),
      // "value": figma.string('value')
    },
    example: props => (
      <InputPassword
        size={props.size}
        disabled={props.disabled}
        isFocused={props.isFocused}
        isInvalid={props.isInvalid}
        defaultValue={props.defaultValue}
        placeholder={props.placeholder}
      />
    ),
  }
);
