import React from "react";
import figma from "@figma/code-connect";
import { Icon } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */
figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:337",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=8042:25",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:336",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=4880:19",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=2224:10497",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:338",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1348:6416",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1057:9500",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=574:10916",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1251:3830",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=564:906",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=176:6325",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=176:6308",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=176:6307",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=176:5822",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=176:5817",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1963",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1964",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1965",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1966",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1967",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1968",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1969",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1970",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1972",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1971",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1962",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1961",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1960",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1959",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1958",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1957",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1956",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1955",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1954",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1953",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1952",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1951",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1950",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1949",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1948",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1947",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1946",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1945",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1944",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1943",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1942",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1941",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1940",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=2788:18541",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=2788:18536",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1939",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1938",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1937",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1936",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:320",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:331",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:328",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:315",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:329",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:316",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:334",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:317",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:318",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:332",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:323",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:335",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:319",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:321",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:322",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:325",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:326",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:327",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:333",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:330",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:324",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=4880:40",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:299",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:300",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:301",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:302",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:303",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:309",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:311",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:312",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:304",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:305",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:306",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:308",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:310",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:307",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:313",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:314",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1306:21385",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:297",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:296",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:298",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1306:21380",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1306:21391",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:292",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:285",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:286",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:287",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:288",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:289",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:291",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:294",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:290",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:293",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:295",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1306:21273",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1935",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1934",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1933",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1932",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1931",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:284",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1930",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1929",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1928",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1927",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:281",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:271",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:273",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:275",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:276",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:274",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:272",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:278",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:279",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:277",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:282",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:280",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:283",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1926",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1925",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1924",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1923",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1922",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1921",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1920",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:270",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1919",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:262",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:266",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:263",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:265",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:261",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:264",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:267",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:268",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=4880:14",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:258",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:255",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:256",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:257",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:259",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:260",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1918",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=5482:14",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:269",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1917",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1916",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1915",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1914",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:252",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:253",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:254",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=174:3439",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=174:3434",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:250",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:251",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1913",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1912",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1911",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1910",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1909",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1908",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1907",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1906",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1905",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1904",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1903",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1902",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1901",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1900",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=17:1899",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:230",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:231",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:232",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:236",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:233",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:241",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:243",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:234",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:235",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:242",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:247",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:248",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:237",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:238",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:239",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:240",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:246",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:244",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:245",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:249",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=4880:35",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=4880:30",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:213",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:221",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:224",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:214",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:215",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:216",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:226",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:220",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:217",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:218",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:229",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:222",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:219",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:225",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:227",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:228",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=15619:223",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=4847:17641",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=4847:17635",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=2207:28",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=2207:25",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);

figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=2207:18",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);
