import React from "react";
import figma from "@figma/code-connect";
import { Tag } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tag,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=558-29098",
  {
    props: {
      variant: figma.enum("variant", {
        solid: "solid",
        outline: "outline",
        subtle: "subtle",
      }),
      size: figma.enum("size", {
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      status: figma.enum("status", {
        neutral: "neutral",
        info: "info",
        success: "success",
        warning: "warning",
        negative: "negative",
      }),
      label: figma.string("label"),
    },
    example: props => (
      <Tag variant={props.variant} size={props.size} status={props.status}>
        {props.label}
      </Tag>
    ),
  }
);
