import React from "react";
import figma from "@figma/code-connect";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogCancel,
  DialogAction,
  DialogIcon,
} from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  "dialog",
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=14857-825",
  {
    props: {
      variant: figma.enum("status", {
        neutral: "neutral",
        warning: "warning",
        negative: "negative",
      }),
      showCloseButton: figma.boolean("showCloseButton"),
      title: figma.string("title"),
      description: figma.string("description"),
    },
    example: props => {
      const iconMap: Record<string, React.ReactNode> = {
        neutral: null,
        warning: <DialogIcon icon="warning" className="text-warning-500" />,
        negative: <DialogIcon icon="error" className="text-negative-400" />,
      };
      return (
        <Dialog>
          <DialogContent showCloseButton={props.showCloseButton}>
            <DialogHeader>
              <DialogTitle>
                {iconMap[props.variant]}
                {props.title}
              </DialogTitle>
              <DialogDescription>{props.description}</DialogDescription>
            </DialogHeader>
            <DialogFooter>
              <DialogCancel>キャンセル</DialogCancel>
              <DialogAction>保存</DialogAction>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      );
    },
  }
);
