import React from "react";
import figma from "@figma/code-connect";
import { Toast } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Toast,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1266%3A13493",
  {
    props: {
      title: figma.string("title"),
      description: figma.string("description"),
      isCloseTrigger: figma.boolean("isCloseTrigger"),
    },
    example: props => (
      <Toast
        title={props.title}
        description={props.description}
        isCloseTrigger={props.isCloseTrigger}
      />
    ),
  }
);
