import React from "react";
import figma from "@figma/code-connect";
import { Toast } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Toast,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1266%3A13444",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      title: figma.boolean("isTitle", {
        true: figma.string("title"),
        false: undefined,
      }),
      description: figma.string("description"),
      isCloseTrigger: figma.boolean("isCloseTrigger"),
      // No matching props could be found for these Figma properties:
      // "isCloseTrigger": figma.boolean('isCloseTrigger'),
      // "isTitle": figma.boolean('isTitle'),
      // "title": figma.string('title'),
      // "description": figma.string('description')
    },
    example: props => (
      <Toast
        title={props.title}
        description={props.description}
        isCloseTrigger={props.isCloseTrigger}
      />
    ),
  }
);
