import * as React from "react";
import { IconButton } from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(IconButton, "", {
  props: {
    state: figma.enum("state", {
      default: "default",
      hover: "hover",
      active: "active",
      disabled: "disabled",
      loading: "loading",
    }),
    variant: figma.enum("variant", {
      solid: "solid",
      outline: "outline-solid",
      ghost: "ghost",
    }),
    size: figma.enum("size", {
      sm: "sm",
      md: "md",
      lg: "lg",
    }),
    theme: figma.enum("theme", {
      primary: "primary",
      secondary: "secondary",
      negative: "negative",
    }),
    children: figma.string("label"),
    icon: figma.string("icon"),
  },
  example: (props) => (
    <IconButton
      variant={props.variant}
      size={props.size}
      theme={props.theme}
      isLoading={props.state === "loading"}
      isDisabled={props.state === "disabled"}
      icon={props.icon}
    >
      {props.children || "Button"}
    </IconButton>
  ),
});

export function examples() {
  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap gap-2">
        <IconButton icon="edit" theme="primary">
          Primary
        </IconButton>
        <IconButton icon="edit" theme="secondary">
          Secondary
        </IconButton>
        <IconButton icon="edit" theme="negative">
          Negative
        </IconButton>
      </div>

      <div className="flex flex-wrap gap-2">
        <IconButton icon="edit" theme="negative">
          Solid
        </IconButton>
        <IconButton icon="edit" theme="negative">
          Outline
        </IconButton>
        <IconButton icon="edit" theme="negative">
          Ghost
        </IconButton>
      </div>

      <div className="flex flex-wrap gap-2">
        <IconButton icon="edit" size="sm">
          Small
        </IconButton>
        <IconButton icon="edit" size="md">
          Medium
        </IconButton>
        <IconButton icon="edit" size="lg">
          Large
        </IconButton>
      </div>

      <div className="flex flex-wrap gap-2">
        <IconButton icon="edit">有効</IconButton>
        <IconButton icon="edit" isLoading>
          Loading
        </IconButton>
        <IconButton icon="edit" isDisabled>
          Disabled
        </IconButton>
      </div>
    </div>
  );
}
