import React from "react";
import figma from "@figma/code-connect";
import { Badge } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1274%3A1622",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("size", {
        xs: "xs",
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      variant: figma.enum("variant", {
        normal: "normal",
        emphasis: "emphasis",
      }),
      isGapped: figma.boolean("isGapped"),
      // No matching props could be found for these Figma properties:
      number: figma.string("number"),
    },
    example: props => (
      <Badge
        size={props.size}
        variant={props.variant}
        isGapped={props.isGapped}
      >
        {props.number}
      </Badge>
    ),
  }
);
