import React from "react";
import figma from "@figma/code-connect";
import { Switch } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Switch,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1075%3A22224",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("size", {
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      disabled: figma.enum("state", {
        disabled: true,
      }),
      checked: figma.boolean("isChecked"),
      defaultChecked: figma.boolean("isChecked"),
      // No matching props could be found for these Figma properties:
      // "isFocused": figma.boolean('isFocused')
    },
    example: props => (
      <Switch
        size={props.size}
        disabled={props.disabled}
        checked={props.checked}
        defaultChecked={props.defaultChecked}
      />
    ),
  }
);
