import React from "react";
import figma from "@figma/code-connect";
import { Input } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Input,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1274%3A63045",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("size", {
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      isDisabled: figma.enum("state", {
        disabled: true,
      }),
      isFocused: figma.boolean("isFocused"),
      isInvalid: figma.boolean("isInvalid"),
      defaultValue: figma.boolean("isEmpty", {
        true: undefined,
        false: figma.string("value"),
      }),
      placeholder: figma.boolean("isEmpty", {
        true: figma.string("value"),
        false: undefined,
      }),
      // No matching props could be found for these Figma properties:
      // "isTrigger": figma.boolean('isTrigger'),
      // "isFocused": figma.boolean('isFocused'),
    },
    example: props => (
      <Input
        size={props.size}
        isDisabled={props.isDisabled}
        isFocused={props.isFocused}
        isInvalid={props.isInvalid}
        defaultValue={props.defaultValue}
        placeholder={props.placeholder}
      />
    ),
  }
);
