import React from "react";
import figma from "@figma/code-connect";
import { Link } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Link,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=825%3A16911",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "isFocused": figma.boolean('isFocused'),
      label: figma.string("label"),
      isOpenInNew: figma.boolean("isOpenInNew"),
      // "state": figma.enum('state', {
      //   "enable": "enable",
      //   "hover": "hover"
      // })
    },
    example: props => (
      <Link href="https://example.com" isExternalLink={props.isOpenInNew}>
        {props.label}
      </Link>
    ),
  }
);
