import React from "react";
import figma from "@figma/code-connect";
import { Textarea } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Textarea,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=2876-24038",
  {
    props: {
      size: figma.enum("size", { sm: "sm", md: "md", lg: "lg" }),
      isInvalid: figma.boolean("isInvalid"),
      isDisabled: figma.enum("state", {
        disabled: true,
      }),
      defaultValue: figma.boolean("isEmpty", {
        true: undefined,
        false: figma.string("value"),
      }),
      placeholder: figma.boolean("isEmpty", {
        true: figma.string("value"),
        false: undefined,
      }),
    },
    example: props => (
      <Textarea
        size={props.size}
        isInvalid={props.isInvalid}
        isDisabled={props.isDisabled}
        placeholder={props.placeholder}
        defaultValue={props.defaultValue}
      />
    ),
  }
);
