import React from "react";
import figma from "@figma/code-connect";
import { IconButton } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  IconButton,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=25%3A906",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      isLoading: figma.enum("state", {
        loading: true,
      }),
      isDisabled: figma.enum("state", {
        disabled: true,
      }),
      disabled: figma.enum("state", {
        disabled: true,
      }),
      variant: figma.enum("variant", {
        solid: "solid",
        outline: "outline",
        ghost: "ghost",
      }),
      size: figma.enum("size", {
        xs: "xs",
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      theme: figma.enum("theme", {
        primary: "primary",
        negative: "negative",
      }),
      // No matching props could be found for these Figma properties:
      // "icon": figma.instance('icon'),
      // "isFocused": figma.boolean('isFocused')
    },
    example: props => (
      <IconButton
        icon="edit"
        isLoading={props.isLoading}
        isDisabled={props.isDisabled}
        disabled={props.disabled}
        variant={props.variant}
        size={props.size}
        theme={props.theme}
      />
    ),
  }
);
