import { client } from "@figma/code-connect";
import fs from "fs";

async function generateIcons() {
  const components = await client.getComponents(
    "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?m=auto&node-id=17-1304"
  );
  const icons = components.filter(component =>
    component.name.startsWith("Icon/")
  );

  fs.writeFileSync(
    "src/components/ui/icon/index.figma.tsx",
    `import React from "react";
import { Icon } from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the \`props\` object to include a mapping from your
 * code props to Figma properties, and update the \`example\` function to
 * return the code example you'd like to see in Figma
 */
${icons
  .map(
    icon => `figma.connect(
  Icon,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=${icon.id}",
  {
    props: {
      icon: figma.textContent("icon"),
      size: 6,
      fill: true,
    },
    example: props => (
      <Icon icon={props.icon} size={props.size} fill={props.fill} />
    ),
  }
);`
  )
  .join("\n\n")}
`
  );
}

generateIcons();
