import React from "react";
import figma from "@figma/code-connect";
import { Radio, RadioItem } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Radio,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=2752%3A17458",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      dir: figma.enum("direction", {
        vertical: "rtl",
      }),
      orientation: figma.enum("direction", {
        horizontal: "horizontal",
        vertical: "vertical",
      }),
      // No matching props could be found for these Figma properties:
      // "units": figma.enum('units', {
      //   "2": "2",
      //   "3": "3",
      //   "4": "4",
      //   "5": "5",
      //   "6": "6",
      //   "7": "7",
      //   "8": "8",
      //   "9": "9"
      // })
    },
    example: props => <Radio dir={props.dir} orientation={props.orientation} />,
  }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  RadioItem,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=176%3A7906",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("size", {
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      isInvalid: figma.enum("isInvalid", {
        false: false,
        true: true,
      }),
      label: figma.string("label"),
      disabled: figma.enum("state", {
        disabled: true,
      }),
      checked: figma.boolean("isChecked"),
      value: figma.string("label"),
      // No matching props could be found for these Figma properties:
      // "isLabel": figma.boolean('isLabel'),
      // "isFocused": figma.boolean('isFocused')
    },
    example: props => (
      <RadioItem
        size={props.size}
        isInvalid={props.isInvalid}
        label={props.label}
        disabled={props.disabled}
        value={props.value}
        checked={props.checked}
      />
    ),
  }
);
