import React from "react";
import {
  InlineMessage,
  InlineMessageDescription,
  InlineMessageTitle,
} from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  InlineMessage,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=1266%3A14202",
  {
    props: {
      title: figma.boolean("isTitle", {
        true: figma.string("title"),
        false: undefined,
      }),
      description: figma.string("description"),
      isCloseTrigger: figma.boolean("isCloseTrigger"),
      status: figma.enum("status", {
        info: "info",
        warning: "warning",
        negative: "negative",
        success: "success",
      }),
    },
    example: props => (
      <InlineMessage
        isCloseTrigger={props.isCloseTrigger}
        status={props.status}
      >
        <InlineMessageTitle>{props.title}</InlineMessageTitle>
        <InlineMessageDescription>{props.description}</InlineMessageDescription>
      </InlineMessage>
    ),
  }
);
