/* eslint-disable react/no-children-prop */
import React from "react";
import figma from "@figma/code-connect";
import { TabsList, TabsTrigger } from "./index";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TabsList,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=234%3A3639",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      variant: figma.enum("variant", {
        solid: "solid",
        line: "line",
        ghost: "ghost",
      }),
      // No matching props could be found for these Figma properties:
      // "units": figma.enum('units', {
      //   "2": "2",
      //   "3": "3",
      //   "4": "4",
      //   "5": "5",
      //   "6": "6",
      //   "7": "7",
      //   "8": "8",
      //   "9": "9"
      // })
    },
    example: props => <TabsList variant={props.variant} />,
  }
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TabsTrigger,
  "https://www.figma.com/design/7alBZXZf65YgcII41TWT0r/Sparkle-Design?node-id=234%3A3608",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("state", {
        disabled: true,
      }),
      label: figma.string("label"),
      variant: figma.enum("variant", {
        line: "line",
        solid: "solid",
        ghost: "ghost",
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('label'),
      // "isSelected": figma.boolean('isSelected')
    },
    example: props => (
      <TabsTrigger
        disabled={props.disabled}
        value={props.label}
        variant={props.variant}
        children={props.label}
      />
    ),
  }
);
